import type { Product, Category } from '@/types';

const PX = (id: string, w = 940, h = 1250) =>
  `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${w}&h=${h}&fit=crop`;

export const mockProducts: Product[] = [
  {
    id: '1',
    slug: 'nova-relaxed-shirt',
    name: 'Nova Relaxed Shirt',
    category: 'shirts',
    categoryLabel: 'Shirts',
    price: 4490,
    description: 'Relaxed-fit shirt in breathable cotton poplin. Designed for everyday movement.',
    details: 'Single chest pocket. Mother-of-pearl buttons. Curved hem.',
    material: '100% organic cotton poplin',
    fit: 'Relaxed fit — true to size',
    colors: ['Black', 'Off-White', 'Charcoal'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('22441297'), PX('22441317')],
    featured: true,
    isNew: true,
  },
  {
    id: '2',
    slug: 'nova-heavyweight-tee',
    name: 'Nova Heavyweight Tee',
    category: 'tshirts',
    categoryLabel: 'T-Shirts',
    price: 2490,
    description: 'Heavyweight cotton tee with a structured drape that holds its shape wash after wash.',
    details: 'Boxy silhouette. Ribbed crew neck. Garment-dyed.',
    material: '280 GSM heavyweight cotton',
    fit: 'Boxy fit — size down for slim',
    colors: ['Black', 'White', 'Stone'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: [PX('8532611'), PX('11671964')],
    isNew: true,
  },
  {
    id: '3',
    slug: 'signature-pleated-trouser',
    name: 'Signature Pleated Trouser',
    category: 'trousers',
    categoryLabel: 'Trousers',
    price: 5990,
    description: 'Single-pleat trouser with a tapered leg. Tailored for comfort and movement.',
    details: 'Single pleat. Side adjusters. Half-lined.',
    material: 'Italian wool-blend twill',
    fit: 'Tapered fit — true to size',
    colors: ['Black', 'Charcoal', 'Stone'],
    sizes: ['28', '30', '32', '34', '36'],
    images: [PX('9464625'), PX('35070984')],
    featured: true,
  },
  {
    id: '4',
    slug: 'relaxed-denim',
    name: 'Relaxed Denim',
    category: 'denim',
    categoryLabel: 'Denim',
    price: 5490,
    description: 'Relaxed straight-leg denim in Japanese selvedge. Raw and honest.',
    details: '14oz selvedge denim. Five-pocket construction. Chain-stitch hem.',
    material: '14 oz Japanese selvedge denim',
    fit: 'Relaxed straight — true to size',
    colors: ['Indigo', 'Washed Black', 'Raw'],
    sizes: ['28', '30', '32', '34', '36'],
    images: [PX('10133274'), PX('7764611')],
    isNew: true,
  },
  {
    id: '5',
    slug: 'structured-overshirt',
    name: 'Structured Overshirt',
    category: 'jackets',
    categoryLabel: 'Jackets',
    price: 6490,
    description: 'A shirt-jacket hybrid in heavyweight twill. Layer it, wear it alone, live in it.',
    details: 'Twin chest pockets. Horn buttons. Reinforced seams.',
    material: 'Heavyweight cotton twill',
    fit: 'Oversized fit — size down for tailored',
    colors: ['Olive', 'Black', 'Stone'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('18919292'), PX('15463481')],
    featured: true,
  },
  {
    id: '6',
    slug: 'harrington-jacket',
    name: 'Harrington Jacket',
    category: 'jackets',
    categoryLabel: 'Jackets',
    price: 8990,
    description: 'A modern take on the classic Harrington. Clean lines, effortless layering.',
    details: 'Tartan lining. Two-way zip. Button collar. Elasticated cuffs.',
    material: 'Water-resistant cotton sateen',
    fit: 'Regular fit — true to size',
    colors: ['Black', 'Navy', 'Stone'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('3911274'), PX('15137845')],
  },
  {
    id: '7',
    slug: 'nova-01-sneaker',
    name: 'Nova 01 Sneaker',
    category: 'sneakers',
    categoryLabel: 'Sneakers',
    price: 7990,
    description: 'Minimal leather sneaker. Clean toe, premium leather, zero branding.',
    details: 'Full-grain leather upper. Margom rubber sole. Leather lining.',
    material: 'Full-grain leather',
    fit: 'True to size',
    colors: ['Black', 'White', 'Bone'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    images: [PX('9666620'), PX('11559288')],
    featured: true,
    isNew: true,
  },
  {
    id: '8',
    slug: 'suede-loafer',
    name: 'Suede Loafer',
    category: 'loafers',
    categoryLabel: 'Loafers',
    price: 8490,
    description: 'Hand-finished suede loafer with a flexible crepe sole. Quiet luxury.',
    details: 'Goodyear-welted. Crepe rubber sole. Leather footbed.',
    material: 'Italian suede',
    fit: 'True to size',
    colors: ['Sand', 'Black', 'Chocolate'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    images: [PX('27204303'), PX('31935097')],
  },
  {
    id: '9',
    slug: 'linen-camp-shirt',
    name: 'Linen Camp Shirt',
    category: 'shirts',
    categoryLabel: 'Shirts',
    price: 3990,
    description: 'Open-collar camp shirt in garment-washed linen. Breathable and lived-in.',
    details: 'Open collar. Straight hem. Box-pleat back.',
    material: '100% European linen',
    fit: 'Relaxed fit — true to size',
    colors: ['Sand', 'Black', 'Sage'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('22441295'), PX('7671168')],
  },
  {
    id: '10',
    slug: 'essential-crew-tee',
    name: 'Essential Crew Tee',
    category: 'tshirts',
    categoryLabel: 'T-Shirts',
    price: 1990,
    description: 'Your everyday tee. Soft, structured, and built to last.',
    details: 'Pre-shrunk. Ribbed collar. Reinforced shoulders.',
    material: '200 GSM combed cotton',
    fit: 'Regular fit — true to size',
    colors: ['White', 'Black', 'Heather'],
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    images: [PX('11671964'), PX('8532611')],
  },
  {
    id: '11',
    slug: 'tapered-chino',
    name: 'Tapered Chino',
    category: 'trousers',
    categoryLabel: 'Trousers',
    price: 4990,
    description: 'Clean, versatile chino with a tapered leg. From desk to dinner.',
    details: 'Slant pockets. Button fly. Back welt pockets.',
    material: 'Stretch cotton twill',
    fit: 'Slim tapered — true to size',
    colors: ['Khaki', 'Black', 'Navy'],
    sizes: ['28', '30', '32', '34', '36'],
    images: [PX('2897533'), PX('7256412')],
  },
  {
    id: '12',
    slug: 'slim-denim',
    name: 'Slim Denim',
    category: 'denim',
    categoryLabel: 'Denim',
    price: 5290,
    description: 'Slim-tapered denim with comfort stretch. Clean, modern, essential.',
    details: '12 oz stretch denim. Five-pocket. Tapered ankle.',
    material: '12 oz stretch cotton denim',
    fit: 'Slim taper — true to size',
    colors: ['Mid Indigo', 'Black', 'Light Wash'],
    sizes: ['28', '30', '32', '34', '36'],
    images: [PX('7764611'), PX('10133278')],
  },
  {
    id: '13',
    slug: 'field-jacket',
    name: 'Field Jacket',
    category: 'jackets',
    categoryLabel: 'Jackets',
    price: 9990,
    description: 'Four-pocket field jacket with a modern cropped silhouette.',
    details: 'Four bellows pockets. Hidden two-way zip. Stowaway hood.',
    material: 'Waxed cotton canvas',
    fit: 'Regular fit — true to size',
    colors: ['Olive', 'Black', 'Sand'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('6699012'), PX('8358794')],
  },
  {
    id: '14',
    slug: 'unstructured-blazer',
    name: 'Unstructured Blazer',
    category: 'blazers',
    categoryLabel: 'Blazers',
    price: 11990,
    description: 'An unlined, unstructured blazer that moves like a cardigan. Tailored, not stiff.',
    details: 'Unlined. Natural shoulder. Patch pockets.',
    material: 'Wool-linen blend',
    fit: 'Tailored fit — true to size',
    colors: ['Charcoal', 'Navy', 'Stone'],
    sizes: ['46', '48', '50', '52'],
    images: [PX('3095442'), PX('27333764')],
    featured: true,
  },
  {
    id: '15',
    slug: 'double-breasted-blazer',
    name: 'Double-Breasted Blazer',
    category: 'blazers',
    categoryLabel: 'Blazers',
    price: 13990,
    description: 'Six-button double-breasted blazer. Sharp, architectural, confident.',
    details: 'Peak lapel. Double vent. Fully canvassed.',
    material: 'Super 120s wool',
    fit: 'Slim fit — true to size',
    colors: ['Black', 'Midnight', 'Charcoal'],
    sizes: ['46', '48', '50', '52'],
    images: [PX('26761830'), PX('4651394')],
  },
  {
    id: '16',
    slug: 'nova-runner-sneaker',
    name: 'Nova Runner Sneaker',
    category: 'sneakers',
    categoryLabel: 'Sneakers',
    price: 6990,
    description: 'Lightweight runner with a chunky sole. Comfort meets minimal design.',
    details: 'Mesh and suede upper. EVA midsole. Rubber outsole.',
    material: 'Mesh, suede, EVA foam',
    fit: 'True to size',
    colors: ['Black', 'Bone', 'Grey'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    images: [PX('20755674'), PX('18972408')],
    isNew: true,
  },
  {
    id: '17',
    slug: 'penny-loafer',
    name: 'Penny Loafer',
    category: 'loafers',
    categoryLabel: 'Loafers',
    price: 7990,
    description: 'Classic penny loafer in polished leather. Timeless, versatile, sharp.',
    details: 'Goodyear-welted. Leather sole. Penny strap detail.',
    material: 'Polished calf leather',
    fit: 'True to size',
    colors: ['Black', 'Oxblood', 'Burgundy'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    images: [PX('10259873'), PX('9992899')],
  },
  {
    id: '18',
    slug: 'oxford-shirt',
    name: 'Oxford Shirt',
    category: 'shirts',
    categoryLabel: 'Shirts',
    price: 3990,
    description: 'The essential oxford cloth button-down. Wears better with every wash.',
    details: 'Button-down collar. Box-pleat back. Locker loop.',
    material: 'Oxford cotton cloth',
    fit: 'Tailored fit — true to size',
    colors: ['White', 'Blue', 'Pink'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('22441317'), PX('22441297')],
  },
  {
    id: '19',
    slug: 'pocket-tee',
    name: 'Pocket Tee',
    category: 'tshirts',
    categoryLabel: 'T-Shirts',
    price: 2290,
    description: 'Minimal pocket tee in midweight cotton. The perfect base layer.',
    details: 'Single chest pocket. Ribbed collar. Pre-washed.',
    material: '220 GSM cotton',
    fit: 'Regular fit — true to size',
    colors: ['Black', 'Stone', 'Olive'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('9594692'), PX('18186105')],
  },
  {
    id: '20',
    slug: 'pleated-wool-trouser',
    name: 'Pleated Wool Trouser',
    category: 'trousers',
    categoryLabel: 'Trousers',
    price: 7490,
    description: 'Double-pleat wool trouser with a wide leg. Drapes beautifully.',
    details: 'Double pleat. Extended tab closure. Wide leg.',
    material: 'Tropical wool',
    fit: 'Wide fit — true to size',
    colors: ['Charcoal', 'Black', 'Stone'],
    sizes: ['28', '30', '32', '34', '36'],
    images: [PX('35070984'), PX('9464625')],
  },
  {
    id: '21',
    slug: 'cargo-denim',
    name: 'Cargo Denim',
    category: 'denim',
    categoryLabel: 'Denim',
    price: 5990,
    description: 'Utility cargo denim with reinforced pockets. Workwear-inspired, city-ready.',
    details: 'Cargo pockets. Reinforced bartacks. Tapered leg.',
    material: '13 oz cotton denim',
    fit: 'Relaxed taper — true to size',
    colors: ['Washed Indigo', 'Black'],
    sizes: ['28', '30', '32', '34', '36'],
    images: [PX('6764124'), PX('17096040')],
    isNew: true,
  },
  {
    id: '22',
    slug: 'bomber-jacket',
    name: 'Bomber Jacket',
    category: 'jackets',
    categoryLabel: 'Jackets',
    price: 9490,
    description: 'Minimal bomber in matte nylon. Clean, lightweight, effortlessly cool.',
    details: 'Ribbed collar and cuffs. Two-way zip. Interior pocket.',
    material: 'Matte nylon shell',
    fit: 'Regular fit — true to size',
    colors: ['Black', 'Navy', 'Sage'],
    sizes: ['S', 'M', 'L', 'XL'],
    images: [PX('17783348'), PX('18919292')],
  },
  {
    id: '23',
    slug: 'knit-blazer',
    name: 'Knit Blazer',
    category: 'blazers',
    categoryLabel: 'Blazers',
    price: 8990,
    description: 'A blazer that wears like a sweater. Soft-shouldered, stretch, zero lining.',
    details: 'Knit construction. No shoulder padding. Two patch pockets.',
    material: 'Stretch wool knit',
    fit: 'Slim fit — true to size',
    colors: ['Black', 'Navy', 'Grey'],
    sizes: ['46', '48', '50', '52'],
    images: [PX('4651539'), PX('3095442')],
  },
  {
    id: '24',
    slug: 'court-sneaker',
    name: 'Court Sneaker',
    category: 'sneakers',
    categoryLabel: 'Sneakers',
    price: 6490,
    description: 'Vintage-inspired court sneaker. Low profile, clean lines, everyday wear.',
    details: 'Leather upper. Cup sole. Padded collar.',
    material: 'Leather and rubber',
    fit: 'True to size',
    colors: ['White', 'Black', 'Green'],
    sizes: ['39', '40', '41', '42', '43', '44'],
    images: [PX('7193629'), PX('9195765')],
  },
];

export function getProducts(): Product[] {
  return mockProducts;
}

export function getProductBySlug(slug: string): Product | undefined {
  return mockProducts.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: Category): Product[] {
  return mockProducts.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return mockProducts.filter((p) => p.featured);
}

export function getNewArrivals(): Product[] {
  return mockProducts.filter((p) => p.isNew);
}

export function getRelatedProducts(slug: string, limit = 6): Product[] {
  const product = getProductBySlug(slug);
  if (!product) return mockProducts.slice(0, limit);
  return mockProducts
    .filter((p) => p.category === product.category && p.slug !== slug)
    .concat(mockProducts.filter((p) => p.category !== product.category))
    .slice(0, limit);
}

export const categories: { id: Category; label: string; number: string; image: string }[] = [
  { id: 'shirts', label: 'Shirts', number: '01', image: PX('22441297') },
  { id: 'trousers', label: 'Trousers', number: '02', image: PX('9464625') },
  { id: 'jackets', label: 'Jackets', number: '03', image: PX('15463481') },
  { id: 'denim', label: 'Denim', number: '04', image: PX('10133274') },
  { id: 'sneakers', label: 'Shoes', number: '05', image: PX('9666620') },
];

export const formatPrice = (price: number): string =>
  `Rs. ${price.toLocaleString('en-IN')}`;
